import { google } from 'googleapis';
import type { AuthClient } from 'google-auth-library';
import { resolveAuth } from './auth.js';
import { GITHUB_OIDC_ISSUER, listWifPools } from './wif.js';
import type { ExportOptions, ExportResult } from './types.js';

/** Turn an id into a Terraform-safe local resource name ([a-z0-9_], leading letter). */
function tfName(raw: string): string {
  const slug = raw.toLowerCase().replace(/[^a-z0-9_]+/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '');
  return /^[a-z]/.test(slug) ? slug : `r_${slug}`;
}

/** Quote a string for HCL (double-quoted, escaped). */
function q(s: string): string {
  return JSON.stringify(s);
}

/** Default/Google-managed SAs we never emit — they aren't user-provisioned. */
function isDefaultServiceAccount(email: string): boolean {
  return (
    /@appspot\.gserviceaccount\.com$/.test(email) ||
    /-compute@developer\.gserviceaccount\.com$/.test(email) ||
    /@cloudservices\.gserviceaccount\.com$/.test(email) ||
    /\.gserviceaccount\.com$/.test(email) === false ||
    /@gcp-sa-/.test(email)
  );
}

async function listEnabledServices(auth: AuthClient, projectId: string): Promise<string[]> {
  const su = google.serviceusage({ version: 'v1', auth: auth as never });
  const out: string[] = [];
  let pageToken: string | undefined;
  do {
    const { data } = await su.services.list({
      parent: `projects/${projectId}`,
      filter: 'state:ENABLED',
      pageSize: 200,
      pageToken,
    });
    for (const s of data.services ?? []) {
      const name = s.config?.name ?? undefined;
      if (name) out.push(name);
    }
    pageToken = data.nextPageToken ?? undefined;
  } while (pageToken);
  return out.sort();
}

async function listUserServiceAccounts(auth: AuthClient, projectId: string): Promise<Array<{ email: string; displayName?: string }>> {
  const iam = google.iam({ version: 'v1', auth: auth as never });
  const out: Array<{ email: string; displayName?: string }> = [];
  let token: string | undefined;
  do {
    const { data } = await iam.projects.serviceAccounts.list({ name: `projects/${projectId}`, pageSize: 100, pageToken: token });
    for (const a of data.accounts ?? []) {
      const email = a.email ?? '';
      if (email && !isDefaultServiceAccount(email)) out.push({ email, displayName: a.displayName ?? undefined });
    }
    token = data.nextPageToken ?? undefined;
  } while (token);
  return out;
}

/**
 * Read a project's current state and render Terraform HCL that would recreate
 * its gcp-seeder-managed surface: the project, its enabled APIs, user-managed
 * service accounts, and any Workload Identity Federation pools/providers.
 *
 * Strictly read-only — this is the "graduation path" off the imperative tool,
 * not an IaC engine. It does not emit secrets (no keys), IAM bindings, or
 * default/Google-managed service accounts.
 */
export async function exportProjectTerraform(options: ExportOptions): Promise<ExportResult> {
  const log = options.logger ?? (() => {});
  const auth = await resolveAuth(options.auth);
  const { projectId } = options;

  log(`Reading ${projectId}…`);
  const crm = google.cloudresourcemanager({ version: 'v3', auth: auth as never });
  const { data: project } = await crm.projects.get({ name: `projects/${projectId}` });
  const [services, serviceAccounts, wifPools] = await Promise.all([
    listEnabledServices(auth, projectId),
    listUserServiceAccounts(auth, projectId),
    listWifPools(auth, projectId).catch(() => []),
  ]);

  const pName = tfName(projectId);
  const displayName = project.displayName ?? projectId;
  const parent = project.parent ?? undefined; // "organizations/123" | "folders/456" | undefined
  const labels = (project.labels ?? {}) as Record<string, string>;

  const blocks: string[] = [];

  blocks.push(
    [
      '# Generated by `gcp-seeder export --terraform`. Review before applying.',
      '# Not an IaC engine — a starting point for managing this project in Terraform.',
      '',
      'terraform {',
      '  required_providers {',
      '    google = {',
      '      source  = "hashicorp/google"',
      '    }',
      '  }',
      '}',
    ].join('\n'),
  );

  const projLines = [`resource "google_project" ${q(pName)} {`, `  project_id = ${q(projectId)}`, `  name       = ${q(displayName)}`];
  if (parent) {
    const [type, id] = parent.split('/');
    if (type === 'organizations') projLines.push(`  org_id = ${q(id ?? '')}`);
    else if (type === 'folders') projLines.push(`  folder_id = ${q(id ?? '')}`);
  }
  if (Object.keys(labels).length) {
    projLines.push('  labels = {');
    for (const [k, v] of Object.entries(labels).sort()) projLines.push(`    ${q(k)} = ${q(v)}`);
    projLines.push('  }');
  }
  projLines.push('}');
  blocks.push(projLines.join('\n'));

  for (const svc of services) {
    blocks.push(
      [
        `resource "google_project_service" ${q(`${pName}_${tfName(svc.split('.')[0] ?? svc)}`)} {`,
        `  project = google_project.${pName}.project_id`,
        `  service = ${q(svc)}`,
        '  disable_on_destroy = false',
        '}',
      ].join('\n'),
    );
  }

  for (const sa of serviceAccounts) {
    const accountId = sa.email.split('@')[0] ?? sa.email;
    blocks.push(
      [
        `resource "google_service_account" ${q(tfName(accountId))} {`,
        `  project      = google_project.${pName}.project_id`,
        `  account_id   = ${q(accountId)}`,
        `  display_name = ${q(sa.displayName ?? accountId)}`,
        '}',
      ].join('\n'),
    );
  }

  for (const pool of wifPools) {
    const poolRes = tfName(`pool_${pool.poolId}`);
    blocks.push(
      [
        `resource "google_iam_workload_identity_pool" ${q(poolRes)} {`,
        `  project                   = google_project.${pName}.project_id`,
        `  workload_identity_pool_id = ${q(pool.poolId)}`,
        ...(pool.displayName ? [`  display_name              = ${q(pool.displayName)}`] : []),
        '}',
      ].join('\n'),
    );
    for (const prov of pool.providers) {
      const provLines = [
        `resource "google_iam_workload_identity_pool_provider" ${q(tfName(`${pool.poolId}_${prov.providerId}`))} {`,
        `  project                            = google_project.${pName}.project_id`,
        `  workload_identity_pool_id          = google_iam_workload_identity_pool.${poolRes}.workload_identity_pool_id`,
        `  workload_identity_pool_provider_id = ${q(prov.providerId)}`,
      ];
      if (prov.attributeCondition) provLines.push(`  attribute_condition = ${q(prov.attributeCondition)}`);
      provLines.push('  oidc {');
      provLines.push(`    issuer_uri = ${q(prov.issuerUri ?? GITHUB_OIDC_ISSUER)}`);
      provLines.push('  }');
      provLines.push('}');
      blocks.push(provLines.join('\n'));
    }
  }

  const hcl = blocks.join('\n\n') + '\n';
  log(`✓ Rendered ${services.length} API(s), ${serviceAccounts.length} service account(s), ${wifPools.length} WIF pool(s).`);
  return {
    projectId,
    hcl,
    counts: { services: services.length, serviceAccounts: serviceAccounts.length, wifPools: wifPools.length },
  };
}
